blank_issues_enabled: false
contact_links:
  - name: More Support At Langfarm GitHub Discussions
    url: https://github.com/langfarm/langfarm/discussions
    about: Please ask and answer questions here.
